#!/usr/bin/env python3
"""Validation, rendering, audit history and atomic apply helpers for V3."""

import argparse
import json
import os
import re
import shutil
import socket
import subprocess
import tempfile
import time
from ipaddress import ip_address
from pathlib import Path


HOST_RE = re.compile(r"^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)*[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$")
RESERVED_PORTS = {10000, 10003}
SENSITIVE_PORTS = {21, 22, 23, 25, 53, 110, 135, 139, 445, 1433, 2375, 3306, 3389, 5432, 6379, 9200, 11211, 27017}


class ConfigError(ValueError):
    pass


def _public_literal(host):
    try:
        value = ip_address(host.strip("[]"))
    except ValueError:
        return True
    return value.is_global


def validate_config(config, resolve=False):
    if config.get("version") != 3:
        raise ConfigError("配置版本必须为 3")
    endpoints = config.get("endpoints", [])
    endpoint_ids = [item.get("id") for item in endpoints]
    if not endpoint_ids or len(endpoint_ids) != len(set(endpoint_ids)):
        raise ConfigError("地址 ID 为空或重复")
    endpoint_map = {item["id"]: item for item in endpoints}
    for endpoint in endpoints:
        host = str(endpoint.get("host", "")).strip().lower()
        port = int(endpoint.get("port", 0))
        if not HOST_RE.match(host) or not _public_literal(host):
            raise ConfigError(f"地址不合法或不是公网地址：{host}")
        if not 1 <= port <= 65535 or port in SENSITIVE_PORTS:
            raise ConfigError(f"上游端口不允许：{host}:{port}")
        if endpoint.get("transport", "tcp") not in {"tcp"}:
            raise ConfigError(f"暂不支持的协议：{endpoint.get('transport')}")
        if host == "ltc.viabtc.com":
            raise ConfigError("ViaBTC 禁止使用错误的 .com 地址")
        if resolve:
            values = {row[4][0] for row in socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)}
            if not values or any(not ip_address(value).is_global for value in values):
                raise ConfigError(f"DNS 解析包含非公网地址：{host}")

    groups = config.get("port_groups", [])
    expected = [
        [9999, 10001, 10002], [10010, 10011, 10012],
        [10020, 10021, 10022], [10030, 10031, 10032],
    ]
    if [item.get("ports") for item in groups] != expected:
        raise ConfigError("四个动态端口组与确认的端口规划不一致")
    ports = []
    references = []
    for group in groups:
        if len(group.get("ports", [])) != 3 or len(group.get("endpoint_ids", [])) != 3:
            raise ConfigError(f"端口组必须包含三个端口和三个上游：{group.get('id')}")
        ports.extend(group["ports"])
        references.extend(group["endpoint_ids"])
    for route in config.get("fixed_routes", []):
        ports.append(int(route["port"]))
        references.append(route["endpoint_id"])
    if len(ports) != len(set(ports)) or RESERVED_PORTS & set(ports):
        raise ConfigError("监听端口重复或占用了保留端口")
    missing = set(references) - set(endpoint_map)
    if missing:
        raise ConfigError("引用了不存在的地址：" + ", ".join(sorted(missing)))
    template_ids = set()
    for template in config.get("templates", []):
        if template.get("id") in template_ids:
            raise ConfigError("模板 ID 重复")
        template_ids.add(template.get("id"))
        if len(template.get("endpoint_ids", [])) != 3:
            raise ConfigError(f"模板必须包含主地址和两个备用地址：{template.get('id')}")
        if set(template["endpoint_ids"]) - set(endpoint_map):
            raise ConfigError(f"模板引用了不存在的地址：{template.get('id')}")
    return True


def render_inspector_config(config, internal_start=20000):
    relays = []
    for offset, endpoint in enumerate(config["endpoints"]):
        if not endpoint.get("enabled", True):
            continue
        relays.append({
            "id": endpoint["id"], "pool_id": endpoint["id"],
            "name": endpoint["pool"], "region": endpoint.get("region", "默认"),
            "role": "地址检查器", "priority": 1, "listen_host": "127.0.0.1",
            "listen_port": internal_start + offset, "upstream_host": endpoint["host"],
            "upstream_port": int(endpoint["port"]), "external": False, "proxy_protocol": True,
        })
    return {"relays": relays}


def route_map(config, internal_start=20000):
    internal = {
        endpoint["id"]: internal_start + offset
        for offset, endpoint in enumerate(config["endpoints"])
        if endpoint.get("enabled", True)
    }
    routes = []
    for group in config["port_groups"]:
        for public_port, endpoint_id in zip(group["ports"], group["endpoint_ids"]):
            routes.append((public_port, endpoint_id, internal[endpoint_id], group["name"]))
    for route in config.get("fixed_routes", []):
        routes.append((int(route["port"]), route["endpoint_id"], internal[route["endpoint_id"]], "固定矿池"))
    return sorted(routes)


def render_haproxy_config(config):
    lines = [
        "# Generated by stratum V3. Do not edit manually.",
        "defaults", "    mode tcp", "    timeout connect 10s",
        "    timeout client 1h", "    timeout server 1h", "",
    ]
    for public_port, endpoint_id, internal_port, group_name in route_map(config):
        safe_id = re.sub(r"[^a-zA-Z0-9_-]", "-", endpoint_id)
        lines.extend([
            f"frontend stratum_v3_{public_port}",
            f"    bind *:{public_port}",
            f"    default_backend stratum_v3_{public_port}_{safe_id}", "",
            f"backend stratum_v3_{public_port}_{safe_id}",
            f"    # {group_name} -> {endpoint_id}",
            f"    server inspector 127.0.0.1:{internal_port} send-proxy", "",
        ])
    return "\n".join(lines)


class ConfigStore:
    def __init__(self, config_path, history_dir, audit_path):
        self.config_path = Path(config_path)
        self.history_dir = Path(history_dir)
        self.audit_path = Path(audit_path)

    def load(self):
        return json.loads(self.config_path.read_text(encoding="utf-8"))

    @staticmethod
    def _atomic_write(path, text, mode=0o640):
        path.parent.mkdir(parents=True, exist_ok=True)
        owner = None
        if path.exists():
            existing = path.stat()
            owner = (existing.st_uid, existing.st_gid)
        fd, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(text)
            os.chmod(temporary, mode)
            if owner and hasattr(os, "chown"):
                os.chown(temporary, owner[0], owner[1])
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)

    def save(self, config, actor="panel", action="save"):
        validate_config(config)
        self.history_dir.mkdir(parents=True, exist_ok=True)
        timestamp = time.strftime("%Y%m%d-%H%M%S") + f"-{time.time_ns() % 1_000_000_000:09d}"
        if self.config_path.exists():
            shutil.copy2(self.config_path, self.history_dir / f"{timestamp}.json")
        self._atomic_write(self.config_path, json.dumps(config, ensure_ascii=False, indent=2) + "\n")
        self.audit_path.parent.mkdir(parents=True, exist_ok=True)
        with self.audit_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps({"time": int(time.time()), "actor": actor, "action": action}, ensure_ascii=False) + "\n")

    def history(self):
        if not self.history_dir.exists():
            return []
        return sorted((item.name for item in self.history_dir.glob("*.json")), reverse=True)

    def rollback(self, name, actor="panel"):
        if Path(name).name != name:
            raise ConfigError("历史版本名称不合法")
        source = self.history_dir / name
        config = json.loads(source.read_text(encoding="utf-8"))
        self.save(config, actor=actor, action=f"rollback:{name}")
        return config

    def read_history(self, name):
        if Path(name).name != name:
            raise ConfigError("历史版本名称不合法")
        return json.loads((self.history_dir / name).read_text(encoding="utf-8"))


def write_generated(config, inspector_path, haproxy_path):
    ConfigStore._atomic_write(Path(inspector_path), json.dumps(render_inspector_config(config), ensure_ascii=False, indent=2) + "\n")
    ConfigStore._atomic_write(Path(haproxy_path), render_haproxy_config(config))


def run_preflight(haproxy_path):
    result = subprocess.run(
        ["haproxy", "-c", "-f", str(haproxy_path)], capture_output=True,
        text=True, timeout=15, check=False,
    )
    if result.returncode:
        raise ConfigError((result.stderr or result.stdout or "HAProxy 配置检查失败")[-1000:])
    return result.stdout.strip()


def main():
    parser = argparse.ArgumentParser(description="Validate and render Stratum V3 configuration")
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--inspector", type=Path, required=True)
    parser.add_argument("--haproxy", type=Path, required=True)
    parser.add_argument("--resolve", action="store_true")
    args = parser.parse_args()
    config = json.loads(args.config.read_text(encoding="utf-8"))
    validate_config(config, resolve=args.resolve)
    write_generated(config, args.inspector, args.haproxy)


if __name__ == "__main__":
    main()
