using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

public static class SupportBundleExporter
{
    private const int MaximumLogCharacters=524288;
    public static void Create(string outputPath,AppConfig config,RelaySnapshot snapshot,IList<MinerSnapshot> miners,string runtimeLog,string storageFolder)
    {
        if(String.IsNullOrWhiteSpace(outputPath))throw new ArgumentException("支持包路径不能为空。");config=LastKnownGoodStore.Clone(config??new AppConfig());config.Normalize();snapshot=snapshot??new RelaySnapshot();miners=miners??new List<MinerSnapshot>();List<string> secrets=new List<string>();foreach(ServerProfile profile in config.Servers)if(profile!=null&&!String.IsNullOrWhiteSpace(profile.SharedKey))secrets.Add(profile.SharedKey);
        Dictionary<string,string> entries=new Dictionary<string,string>();StringBuilder report=new StringBuilder();report.AppendLine("木林森中转脱敏技术支持包");report.AppendLine("生成时间："+DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));report.AppendLine("程序版本："+AppBrand.Version);report.AppendLine("Windows："+Environment.OSVersion);report.AppendLine("电脑标识："+Marker(Environment.MachineName));report.AppendLine("连续运行："+SystemStatus.Uptime);report.AppendLine("矿场："+Sanitize(config.SiteName,secrets,config));report.AppendLine("监听地址："+MaskIp(config.ListenAddress));report.AppendLine("端口："+config.Ports);report.AppendLine("中转运行："+snapshot.Running);report.AppendLine("当前连接："+snapshot.Active);report.AppendLine("在线矿机："+snapshot.ActiveMiners);report.AppendLine("失败重连："+snapshot.Failures);report.AppendLine("上传/下载："+snapshot.Uploaded+" / "+snapshot.Downloaded);foreach(ServerProfile profile in config.Servers)if(profile!=null&&profile.Enabled)report.AppendLine("VPS："+Sanitize(profile.Name,secrets,config)+"；地址标识="+Marker(profile.Address+":"+profile.Port)+"；证书="+ShortFingerprint(profile.CertificateSha256));entries["report.txt"]=Sanitize(report.ToString(),secrets,config);
        StringBuilder timeline=new StringBuilder("miner,endpoint,connections,health,submitted,accepted,rejected,last_activity,last_share,disconnects,failures\r\n");foreach(MinerSnapshot miner in miners){timeline.Append(Marker(miner.Ip)).Append(',').Append(Csv(miner.Endpoint)).Append(',').Append(miner.Connections).Append(',').Append(miner.Health).Append(',').Append(miner.Submitted).Append(',').Append(miner.Accepted).Append(',').Append(miner.Rejected).Append(',').Append(miner.LastActivity.ToString("O")).Append(',').Append(miner.LastAccepted==DateTime.MinValue?"":miner.LastAccepted.ToString("O")).Append(',').Append(miner.Disconnects).Append(',').Append(miner.Failures).Append("\r\n");}entries["connection-timeline.csv"]=Sanitize(timeline.ToString(),secrets,config);
        StringBuilder logs=new StringBuilder();AppendBounded(logs,"【当前运行记录】",runtimeLog);if(!String.IsNullOrWhiteSpace(storageFolder)&&Directory.Exists(storageFolder)){foreach(string pattern in new[]{"crash.log","diagnostic-*.txt","remote-diagnostic-*.txt","update-error.log","service-status.txt"})foreach(string path in Directory.GetFiles(storageFolder,pattern)){AppendBounded(logs,"【"+Path.GetFileName(path)+"】",ReadBounded(path));if(logs.Length>=MaximumLogCharacters)break;}}entries["logs.txt"]=Sanitize(logs.ToString(),secrets,config);
        foreach(KeyValuePair<string,string> entry in entries)EnsureSafe(entry.Value,secrets,config);StringBuilder manifest=new StringBuilder();foreach(KeyValuePair<string,string> entry in entries)manifest.Append(Hash(entry.Value)).Append("  ").Append(entry.Key).AppendLine();entries["manifest.txt"]=manifest.ToString();
        string full=Path.GetFullPath(outputPath),temporary=full+".tmp";Directory.CreateDirectory(Path.GetDirectoryName(full));if(File.Exists(temporary))File.Delete(temporary);try{using(FileStream stream=new FileStream(temporary,FileMode.CreateNew,FileAccess.ReadWrite,FileShare.None))using(ZipArchive archive=new ZipArchive(stream,ZipArchiveMode.Create)){foreach(KeyValuePair<string,string> entry in entries){ZipArchiveEntry item=archive.CreateEntry(entry.Key,CompressionLevel.Optimal);using(StreamWriter writer=new StreamWriter(item.Open(),new UTF8Encoding(false)))writer.Write(entry.Value);}}if(File.Exists(full))File.Replace(temporary,full,null);else File.Move(temporary,full);}finally{if(File.Exists(temporary))try{File.Delete(temporary);}catch{}}
    }
    public static string Sanitize(string text,IList<string> secrets,AppConfig config)
    {
        string value=text??"";if(secrets!=null)foreach(string secret in secrets)if(!String.IsNullOrWhiteSpace(secret))value=value.Replace(secret,"<redacted-secret>");if(config!=null&&config.Servers!=null)foreach(ServerProfile profile in config.Servers)if(profile!=null&&!String.IsNullOrWhiteSpace(profile.Address))value=value.Replace(profile.Address,"<vps-address:"+Marker(profile.Address)+">");value=Regex.Replace(value,"-----BEGIN [^-]*PRIVATE KEY-----[\\s\\S]*?-----END [^-]*PRIVATE KEY-----","<redacted-private-key>",RegexOptions.IgnoreCase);value=Regex.Replace(value,"(?im)(authorization\\s*:\\s*bearer\\s+)[^\\s]+","$1<redacted-secret>");value=Regex.Replace(value,"(?im)((?:password|token|secret|shared[_ -]?key)\\s*[:=]\\s*)[^\\s,;]+","$1<redacted-secret>");value=Regex.Replace(value,@"(?<![A-Za-z0-9])(?:25[0-5]|2[0-4]\d|1?\d?\d)(?:\.(?:25[0-5]|2[0-4]\d|1?\d?\d)){3}(?![A-Za-z0-9])",delegate(Match match){return MaskIp(match.Value);});value=Regex.Replace(value,@"(?i)C:\\Users\\[^\\\r\n]+",@"C:\Users\<redacted-user>");return value;
    }
    private static void EnsureSafe(string value,IList<string> secrets,AppConfig config){if(secrets!=null)foreach(string secret in secrets)if(!String.IsNullOrWhiteSpace(secret)&&value.Contains(secret))throw new InvalidDataException("支持包仍包含共享密钥，已停止导出。");if(Regex.IsMatch(value,"BEGIN [^-]*PRIVATE KEY",RegexOptions.IgnoreCase))throw new InvalidDataException("支持包仍包含证书私钥，已停止导出。");if(config!=null&&config.Servers!=null)foreach(ServerProfile profile in config.Servers)if(profile!=null&&!String.IsNullOrWhiteSpace(profile.Address)&&value.Contains(profile.Address))throw new InvalidDataException("支持包仍包含完整 VPS 地址，已停止导出。");}
    private static string Marker(string value){if(String.IsNullOrWhiteSpace(value))return "-";using(SHA256 sha=SHA256.Create()){byte[] digest=sha.ComputeHash(Encoding.UTF8.GetBytes(value));StringBuilder text=new StringBuilder();for(int i=0;i<6;i++)text.Append(digest[i].ToString("X2"));return text.ToString();}}
    private static string MaskIp(string value){System.Net.IPAddress address;if(!System.Net.IPAddress.TryParse(value,out address))return value??"";byte[] bytes=address.GetAddressBytes();return bytes.Length==4?bytes[0]+"."+bytes[1]+"."+bytes[2]+".x":"<redacted-ip>";}
    private static string ShortFingerprint(string value){string clean=Regex.Replace(value??"","[^A-Fa-f0-9]","").ToUpperInvariant();return clean.Length>=12?clean.Substring(0,12)+"…":"未提供";}
    private static string Csv(string value){return "\\\""+(value??"").Replace("\\\"","\\\"\\\"")+"\\\"";}
    private static string Hash(string value){using(SHA256 sha=SHA256.Create()){byte[] digest=sha.ComputeHash(Encoding.UTF8.GetBytes(value??""));StringBuilder text=new StringBuilder();foreach(byte item in digest)text.Append(item.ToString("x2"));return text.ToString();}}
    private static string ReadBounded(string path){try{string value=File.ReadAllText(path,Encoding.UTF8);return value.Length>MaximumLogCharacters?value.Substring(value.Length-MaximumLogCharacters):value;}catch(Exception ex){return "无法读取："+ex.GetType().Name;}}
    private static void AppendBounded(StringBuilder output,string title,string value){if(output.Length>=MaximumLogCharacters)return;output.AppendLine(title);string text=value??"";int remaining=MaximumLogCharacters-output.Length;if(text.Length>remaining)text=text.Substring(text.Length-remaining);output.AppendLine(text);}
}
